version: '3.8'

services:
    mysql:
        image: mysql:8.0.39
        container_name: maintenance-container
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
        ports:
            - 3306:3306
        volumes:
            - ./mysql-data:/var/lib/mysql