export enum Message {
    ROLE_OBTAINED_SUCCESSFULLY = "COD001",
    NOT_ROLES_FOUND = "COD002",
    ACTOR_CREATED_SUCCESSFULLY = "COD003",
    BAD_REQUEST = "COD009",
    INTERNAL_SERVER_ERROR = "COD010",
}