export enum Message {
  ROLES_OBTAINED_SUCCESSFULLY = "COD001",
  ACTOR_CREATED_SUCCESSFULLY = "COD002",
  ACTORS_OBTAINED_SUCCESSFULLY = "COD003",
  ACTOR_OBTAINED_SUCCESSFULLY = "COD004",
  ACTOR_UPDATED_SUCCESSFULLY = "COD005",

  DEPARTMENT_CREATED_SUCCESSFULLY = "COD006",
  DEPARTMENTS_OBTAINED_SUCCESSFULLY = "COD007",
  DEPARTMENT_UPDATED_SUCCESSFULLY = "COD008",

  MAINTENANCE_CREATED_SUCCESSFULLY = "COD09",
  MAINTENANCES_OBTAINED_SUCCESSFULLY = "COD010",
  MAINTENANCE_OBTAINED_SUCCESSFULLY = "COD011",
  MAINTENANCE_UPDATED_SUCCESSFULLY = "COD012",

  NOT_ROLES_FOUND = "COD020",
  ACTOR_ALREADY_EXISTS_EXCEPTION = "COD021",
  COORDINATOR_ALREADY_EXISTS = "COD022",
  NOT_COORDINATOR_FOUND = "COD023",
  NOT_ACTORS_FOUND = "COD024",
  NOT_ACTOR_FOUND = "COD025",

  BAD_REQUEST = "COD050",
  INTERNAL_SERVER_ERROR = "COD100",
}
