export enum Message {
  ROLES_OBTAINED_SUCCESSFULLY = "COD001",
  NOT_ROLES_FOUND = "COD002",
  ACTOR_CREATED_SUCCESSFULLY = "COD003",
  ACTORS_OBTAINED_SUCCESSFULLY = "COD004",
  BAD_REQUEST = "COD009",
  INTERNAL_SERVER_ERROR = "COD010",
}
